{
    '*.{js,mjs,cjs,ts,mts,cts}': ['eslint --fix', prettier --write'],
    '*.scss': ['stylelint --fix', prettier --write'],
    '!(*.{js,mjs,cjs,ts,mts,cts}|*.scss)': 'prettier --ignore-unknown --write',
}
